# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplteStockDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_num', models.IntegerField(unique=True)),
                ('item_name', models.CharField(max_length=50, unique=True)),
                ('company', models.CharField(max_length=30)),
                ('price_per_unit', models.FloatField()),
                ('manf_data', models.CharField(max_length=10)),
                ('exp_data', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DealersInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('dl1', models.CharField(max_length=15, unique=True)),
                ('dl2', models.CharField(max_length=15, unique=True)),
                ('tin', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, unique=True)),
                ('pwd', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20, unique=True)),
                ('last_name', models.CharField(max_length=20, unique=True)),
                ('age', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='dealersinfo',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.Person'),
        ),
        migrations.AddField(
            model_name='compltestockdetails',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.DealersInfo'),
        ),
    ]
